/**
 *
 * @author pc
 */



import java.io.BufferedReader;
import java.io.FileReader;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class OUTPUT extends javax.swing.JFrame {

                 /*public void  READ_LOG(String filename )throws TException{
                     
                     try{
                         BufferedReader in=new BufferedReader(new FileReader(filename));
                         
                         String line;
                         line=in.readLine();
                        
                         NAME_in.setText(line);
                         
                         
                         
                        in.close(); 
                     }catch(Exception e)
                 {
                     throw new TException("Error file location"+e.getMessage());
    } */
                 

    
     Teacher x=new Teacher();
     String filenameT;
        
    public OUTPUT() {
        initComponents();
        //System.exit(0);
        filenameT ="Data.txt";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        SUBJECT3_in = new javax.swing.JTextField();
        NAME_in = new javax.swing.JTextField();
        SUBJECT2_in = new javax.swing.JTextField();
        ID_in = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EMAIL_in = new javax.swing.JTextField();
        SUBJECT1_in = new javax.swing.JTextField();
        MOB_in = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SALARY_in = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SHOW_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Subject 2");

        SUBJECT3_in.setText(" ");
        SUBJECT3_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBJECT3_inActionPerformed(evt);
            }
        });

        NAME_in.setText(" ");
        NAME_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME_inActionPerformed(evt);
            }
        });

        SUBJECT2_in.setText(" ");
        SUBJECT2_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBJECT2_inActionPerformed(evt);
            }
        });

        ID_in.setText(" ");
        ID_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_inActionPerformed(evt);
            }
        });

        jLabel5.setText("Email");

        jLabel8.setText("Subject 1");

        jLabel6.setText("Mob Number");

        EMAIL_in.setText(" ");
        EMAIL_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAIL_inActionPerformed(evt);
            }
        });

        SUBJECT1_in.setText(" ");
        SUBJECT1_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBJECT1_inActionPerformed(evt);
            }
        });

        MOB_in.setText(" ");
        MOB_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOB_inActionPerformed(evt);
            }
        });

        jLabel7.setText("Salary");

        jLabel3.setText("Name");

        jLabel10.setText("Subject 3");

        SALARY_in.setText(" ");
        SALARY_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALARY_inActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        SHOW_Button.setText("SHOW");
        SHOW_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NAME_in)
                            .addComponent(ID_in)
                            .addComponent(EMAIL_in)
                            .addComponent(MOB_in)
                            .addComponent(SALARY_in)
                            .addComponent(SUBJECT1_in)
                            .addComponent(SUBJECT2_in, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(SUBJECT3_in, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(SHOW_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAME_in, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_in, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EMAIL_in, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOB_in, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALARY_in, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SUBJECT1_in, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SUBJECT2_in)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SUBJECT3_in, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(SHOW_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SUBJECT3_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBJECT3_inActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SUBJECT3_inActionPerformed

    private void NAME_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME_inActionPerformed
        // TODO add your handling code here:]

    }//GEN-LAST:event_NAME_inActionPerformed

    private void SUBJECT2_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBJECT2_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUBJECT2_inActionPerformed

    private void ID_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_inActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ID_inActionPerformed

    private void EMAIL_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAIL_inActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EMAIL_inActionPerformed

    private void SUBJECT1_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBJECT1_inActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SUBJECT1_inActionPerformed

    private void MOB_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOB_inActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_MOB_inActionPerformed

    private void SALARY_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALARY_inActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SALARY_inActionPerformed

    private void SHOW_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_ButtonActionPerformed
        // TODO add your handling code here:
        
       /* OUTPUT x=new OUTPUT();
    try{
        x.READ_LOG(filenameT); 
        
    }catch(Exception eee){
            
        JOptionPane.showMessageDialog(null," " +eee.getMessage());
    }
        */
       
          try{
                         BufferedReader in=new BufferedReader(new FileReader(filenameT));
                         
                         String line;
                         line=in.readLine();
                   /*   LinkedList<String> lines = new LinkedList<String>();
                         
                      while(line != null){ 
                         lines.add(line);  
                         line = in.readLine();
                            }*/
                   
                         NAME_in.setText(line);
                         line=in.readLine();
                         ID_in.setText(line);
                         line=in.readLine();
                         EMAIL_in.setText(line);
                         line=in.readLine();
                         MOB_in.setText(line);
                         line=in.readLine();
                         SALARY_in.setText(line);
                         line=in.readLine();
                         SUBJECT1_in.setText(line);
                         line=in.readLine();
                         SUBJECT2_in.setText(line);
                         line=in.readLine();  
                         SUBJECT3_in.setText(line);
                         line=in.readLine();  
                                                                                                           
                           
                        in.close(); 
                     }catch(Exception e)
                 {
                      JOptionPane.showMessageDialog(null," ERROR" );
                 }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_SHOW_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OUTPUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OUTPUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OUTPUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OUTPUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OUTPUT().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField EMAIL_in;
    private javax.swing.JTextField ID_in;
    public javax.swing.JTextField MOB_in;
    public javax.swing.JTextField NAME_in;
    public javax.swing.JTextField SALARY_in;
    private javax.swing.JButton SHOW_Button;
    public javax.swing.JTextField SUBJECT1_in;
    public javax.swing.JTextField SUBJECT2_in;
    public javax.swing.JTextField SUBJECT3_in;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}

